on:
  release:
    types: [created]
  push:

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: JosephNaberhaus/actions/release-go-binary@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: -X "main.version=${{ env.RELEASE_VERSION }}"
